  CAMERA_DIMENSIONS : [16, 9]
  SCREEN_WIDTH : 1024
  SCREEN_HEIGHT :  576
  GAME_WIDTH : 32
  GAME_HEIGHT :  9
  PLAYER_DIMENSIONS : [0.7, 0.9]
  PLAYER_VELOCITY : [0.07, 0.5]
  PLAYER_VELOCITY_MAX : [3.0, 4.0]
  JUMP_COOLDOWN : 0.
  IN_AIR_PENALTY_X : 0.1
  GRAVITY_Y : 0.03
  DRAG_COEFFICIENT : [0.6, 0.95]