use ggez::{Context, GameResult};
use ggez::error::GameError;
use ggez::graphics;
use ggez::nalgebra as na;

use std::cell::RefCell;
use std::ops::Index;

use crate::assets::Texture;
use crate::collider::ColliderEdge;
use crate::block::Block;

pub struct TileMap {
    width : usize,
    height: usize,
    grid  : Vec<Block>,
    spritebatch: RefCell<graphics::spritebatch::SpriteBatch>,
}

impl TileMap {
    pub fn new(width: usize, height: usize, grid: Vec<Block>, spritebatch: graphics::spritebatch::SpriteBatch) -> GameResult<TileMap> {
        if grid.len() != height * width {
            return Err(GameError::ResourceLoadError(String::from("TileMap has wrong dimensions")));
        }

        Ok(TileMap {
            width : width,
            height: height,
            grid  : grid,
            spritebatch: RefCell::new(spritebatch),
        })
    }

    pub fn blocks(&self) -> impl Iterator<Item = ((usize,usize), &Block)> {
        self.grid
            .iter()
            .as_slice()
            .chunks(self.width)
            .enumerate()
            .flat_map(|(y_idx, row)| row.iter().enumerate().map(move |(x_idx, block)| ((x_idx, y_idx), block)))
    }

    pub fn textures(&self) -> impl Iterator<Item = ((usize,usize), &Texture)> {
        self.blocks().map(move |((x,y),block)| ((x,y), &block.texture))
    }

    pub fn colliders(&self) -> impl Iterator<Item = ((usize,usize), &ColliderEdge)> {
        self.blocks().map(move |((x,y),block)| ((x,y), &block.collider))
    }

    //Pass width and height because SpriteBatch doesn't have a getter for image
    pub fn draw(&self, ctx: &mut Context, camera: graphics::DrawParam) -> GameResult<()> {
        

        for((x,y),texture) in self.textures() {
            let x = x as f32;
            let y = y as f32;
            let p = graphics::DrawParam{
                dest:  na::Point2::new(x, y),
                scale: na::Point2::new(1.0 / 171.0, //??? why no getter for image?!!
                                       1.0 / 167.0), //???
                ..
                Default::default()
            };

            match texture {
                Texture::Ground => {self.spritebatch.borrow_mut().add(p);},
                _ => {},
            };
        };

        graphics::draw_ex(ctx, &*self.spritebatch.borrow(), camera)?;
        self.spritebatch.borrow_mut().clear();
        Ok(())
    }

    pub fn load_test(spritebatch: graphics::spritebatch::SpriteBatch) -> TileMap {

        // let vec = vec![
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},
        // ];

        let vec = vec![
            Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
            Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
            Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
            Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
            Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
            Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
            Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
            Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},Block { texture: Texture::Air,  collider: ColliderEdge::none()},
            Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},Block { texture: Texture::Ground,  collider: ColliderEdge::all()},
        ];

        // let vec = vec!
        // [
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()}, Block { texture: Texture::Air,  collider: ColliderEdge::none()},
        //     Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()}, Block { texture: Texture::Ground,  collider: ColliderEdge::none().top()},     
        // ];        

        TileMap::new(32, 9, vec, spritebatch).unwrap()
    } 
}

impl Index<(usize,usize)> for TileMap {
    type Output = Block;
    fn index(&self, (x,y): (usize, usize)) -> &Block {
        &self.grid[(y * self.width) + x ]
    }
}